# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En proceso'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], default='IN_PROGRESS', max_length=20)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de idempotencia',
                'verbose_name_plural': 'Registros de idempotencia',
                'db_table': 'payments_idempotency_record',
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_id_status_b3b417_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='api_idempotencyrecord_scope_key_uniq')],
            },
        ),
    ]
