# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import samy_common.states
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('requested_by_id', models.UUIDField(db_index=True)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operator_name', models.CharField(max_length=100)),
                ('product_label', models.CharField(max_length=160)),
                ('phone_e164', models.CharField(max_length=20)),
                ('phone_masked', models.CharField(max_length=20)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('amount_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('state', models.CharField(choices=[('PENDING_PAYMENT', 'PENDING_PAYMENT'), ('QUEUED', 'QUEUED'), ('SENT', 'SENT'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('REVERSED', 'REVERSED')], db_index=True, default=samy_common.states.FulfillmentState['PENDING_PAYMENT'], max_length=24)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_reason', models.CharField(blank=True, default='', max_length=255)),
                ('provider_slug', models.CharField(blank=True, default='', max_length=40)),
                ('provider_mode', models.CharField(blank=True, default='', max_length=16)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('operator_reference', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='catalog.topupproduct')),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_id', '-created_at'], name='fulfillment_store_i_7c27a4_idx'), models.Index(fields=['state', 'created_at'], name='fulfillment_state_4029a0_idx'), models.Index(condition=models.Q(('state', 'UNDER_REVIEW')), fields=['created_at'], name='topup_needs_recon_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['PENDING_PAYMENT', 'QUEUED', 'SENT', 'SUCCEEDED', 'FAILED', 'UNDER_REVIEW', 'REVERSED'])), name='fulfillment_state_is_valid'), models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='fulfillment_amount_positive')],
            },
        ),
    ]
