# Generated by Django 5.2.17 on 2026-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupfulfillment',
            name='economia',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
