# Generated by Django 5.2.17 on 2026-09-05 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Inicio de sesion'), ('LOGIN_FAILED', 'Inicio de sesion fallido'), ('LOGOUT', 'Cierre de sesion'), ('PASSWORD_RESET_REQUESTED', 'Solicitud de nueva contrasena'), ('PASSWORD_CHANGED', 'Contrasena modificada'), ('PERMISSION_DENIED', 'Acceso denegado'), ('STORE_SWITCHED', 'Cambio de tienda'), ('ORDER_CREATED', 'Orden creada'), ('ORDER_STATE_CHANGED', 'Cambio de estado de orden'), ('PAYMENT_ATTEMPTED', 'Intento de pago'), ('PAYMENT_CONFIRMED', 'Pago confirmado'), ('FULFILLMENT_REQUESTED', 'Servicio solicitado al proveedor'), ('FULFILLMENT_RESULT', 'Respuesta del proveedor'), ('REFUND_REQUESTED', 'Reembolso solicitado'), ('CONFIG_CHANGED', 'Configuracion modificada'), ('COMMISSION_RULE_CHANGED', 'Regla de comision modificada'), ('PROVIDER_CONFIG_CHANGED', 'Proveedor reconfigurado'), ('EMPLOYEE_ADDED', 'Empleado agregado'), ('EMPLOYEE_REMOVED', 'Empleado dado de baja')], db_index=True, max_length=48)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('actor_role', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('previous_state', models.CharField(blank=True, default='', max_length=32)),
                ('new_state', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tenancy.store')),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='audit_audit_store_i_85d606_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_9e2202_idx')],
            },
        ),
    ]
