# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('provider_mode', models.CharField(blank=True, default='', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('operators_found', models.PositiveIntegerField(default=0)),
                ('products_found', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('products_deactivated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Sincronizacion de catalogo',
                'verbose_name_plural': 'Sincronizaciones de catalogo',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['provider_slug', '-started_at'], name='catalog_cat_provide_37596a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('provider_operator_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=60)),
                ('country_code', models.CharField(default='MX', max_length=2)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('supports_data_packages', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='catalog_ope_is_acti_ab1823_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'provider_operator_id'), name='operator_unique_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='TopupProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('provider_product_id', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('max_amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('is_data_package', models.BooleanField(default=False)),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.operator')),
            ],
            options={
                'verbose_name': 'Producto de recarga',
                'verbose_name_plural': 'Productos de recarga',
                'ordering': ['operator__display_order', 'amount_cents', 'label'],
                'indexes': [models.Index(fields=['operator', 'is_active', 'amount_cents'], name='catalog_top_operato_fde305_idx'), models.Index(fields=['is_active', 'last_seen_at'], name='catalog_top_is_acti_f1b858_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'provider_product_id'), name='product_unique_per_provider'), models.CheckConstraint(condition=models.Q(('amount_cents__isnull', False), models.Q(('min_amount_cents__isnull', False), ('max_amount_cents__isnull', False)), _connector='OR'), name='product_has_amount_or_range')],
            },
        ),
    ]
