# Generated by Django 5.2.17 on 2026-09-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsyncrun',
            name='operators_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
