# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('provider_biller_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Luz'), ('WATER', 'Agua'), ('GAS', 'Gas'), ('TELECOM', 'Telefonia e internet'), ('TV', 'Television'), ('OTHER', 'Otros')], max_length=20)),
                ('coverage_note', models.CharField(blank=True, default='', max_length=160)),
                ('state_code', models.CharField(blank=True, default='', max_length=4)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('supports_inquiry', models.BooleanField(default=False)),
                ('supports_partial_payment', models.BooleanField(default=False)),
                ('min_amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('max_amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category', 'display_order'], name='billers_bil_is_acti_566956_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'provider_biller_id'), name='biller_unique_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceFormat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Referencia', help_text="Como se llama en el recibo: 'Numero de servicio', 'Contrato'...", max_length=80)),
                ('help_text', models.CharField(blank=True, default='', help_text='Donde encontrarlo en el recibo. Se muestra al cajero.', max_length=200)),
                ('min_length', models.PositiveSmallIntegerField(default=1)),
                ('max_length', models.PositiveSmallIntegerField(default=40)),
                ('validation_regex', models.CharField(blank=True, default='', max_length=200)),
                ('numeric_only', models.BooleanField(default=True)),
                ('barcode_formats', models.JSONField(blank=True, default=list, help_text="Ej. ['code_128', 'itf']. Vacio = se prueban todas.")),
                ('barcode_extraction_regex', models.CharField(blank=True, default='', max_length=200)),
                ('example', models.CharField(blank=True, default='', max_length=60)),
                ('specification_source', models.CharField(blank=True, default='', help_text="De donde se obtuvo. 'Pendiente' si aun no hay documentacion oficial.", max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_format', to='billers.biller')),
            ],
            options={
                'verbose_name': 'Formato de referencia',
                'verbose_name_plural': 'Formatos de referencia',
            },
        ),
    ]
