# Generated by Django 5.2.17 on 2026-09-05 19:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('outcome', models.CharField(blank=True, default='', max_length=16)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('APPLIED', 'Aplicado'), ('DUPLICATE', 'Duplicado ignorado'), ('ORDER_NOT_FOUND', 'Sin orden asociada'), ('REJECTED', 'Rechazado'), ('IGNORED', 'Sin efecto (estado no terminal)')], default='IGNORED', max_length=24)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Webhook recibido',
                'verbose_name_plural': 'Webhooks recibidos',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider_slug', '-received_at'], name='webhooks_re_provide_0c7de8_idx'), models.Index(fields=['event_type', '-received_at'], name='webhooks_re_event_t_0873e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'event_id'), name='webhook_unique_per_provider_event')],
            },
        ),
    ]
