# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('provider_mode', models.CharField(max_length=16)),
                ('method', models.CharField(max_length=16)),
                ('amount_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Iniciado'), ('AWAITING_CUSTOMER', 'Esperando al cliente'), ('CONFIRMED', 'Confirmado'), ('DECLINED', 'Rechazado'), ('EXPIRED', 'Expirado'), ('INDETERMINATE', 'Indeterminado')], db_index=True, default='INITIATED', max_length=24)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=500)),
                ('declined_reason', models.CharField(blank=True, default='', max_length=255)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='orders.order')),
            ],
            options={
                'verbose_name': 'Intento de pago',
                'verbose_name_plural': 'Intentos de pago',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='payments_pa_order_i_37df30_idx'), models.Index(fields=['provider_slug', 'provider_reference'], name='payments_pa_provide_82a77a_idx'), models.Index(condition=models.Q(('status', 'INDETERMINATE')), fields=['status', 'created_at'], name='attempt_needs_recon_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentQrToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nonce', models.CharField(max_length=32)),
                ('amount_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('store_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='orders.order')),
            ],
            options={
                'verbose_name': 'Token QR de cobro',
                'verbose_name_plural': 'Tokens QR de cobro',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('consumed_at__isnull', True)), fields=['expires_at'], name='qr_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='qr_expires_after_creation')],
            },
        ),
    ]
