# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField()),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PUBLISHED', 'Publicado'), ('FAILED', 'Fallido')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Evento de outbox',
                'verbose_name_plural': 'Eventos de outbox',
                'db_table': 'payments_outbox_event',
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('status', 'PENDING')), fields=['next_attempt_at'], name='outbox_outboxevent_due_idx')],
            },
        ),
    ]
