# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('service_kind', models.CharField(choices=[('TOPUP', 'Recarga telefonica'), ('BILL_PAYMENT', 'Pago de servicios'), ('MERCHANT_SALE', 'Venta del comercio')], max_length=24)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('store_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('product_code', models.CharField(blank=True, default='', max_length=64)),
                ('commission_type', models.CharField(choices=[('FIXED', 'Monto fijo'), ('PERCENTAGE', 'Porcentaje'), ('MIXED', 'Fijo + porcentaje')], max_length=16)),
                ('fixed_cents', models.BigIntegerField(default=0, help_text='Componente fijo en centavos. 1000 = $10.00 MXN.', validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Puntos porcentuales. 2.500 = 2.5%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('min_cents', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_cents', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regla de comision',
                'verbose_name_plural': 'Reglas de comision',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['service_kind', 'is_active'], name='commissions_service_a88d03_idx'), models.Index(fields=['store_id', 'service_kind', 'is_active'], name='commissions_store_i_a1b69e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_cents__isnull', True), ('min_cents__isnull', True), ('max_cents__gte', models.F('min_cents')), _connector='OR'), name='commission_max_gte_min'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='commission_valid_range')],
            },
        ),
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_weight', models.PositiveIntegerField(default=60, help_text='Peso de la ganancia de la tienda.')),
                ('platform_weight', models.PositiveIntegerField(default=30, help_text='Peso de la comision de SAMY Cloud.')),
                ('provider_weight', models.PositiveIntegerField(default=10, help_text='Peso reservado para el costo del proveedor.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split', to='commissions.commissionrule')),
            ],
            options={
                'verbose_name': 'Reparto de comision',
                'verbose_name_plural': 'Repartos de comision',
                'constraints': [models.CheckConstraint(condition=models.Q(('store_weight__gt', 0), ('platform_weight__gt', 0), ('provider_weight__gt', 0), _connector='OR'), name='commission_split_nonzero')],
            },
        ),
    ]
