# Generated by Django 5.2.17 on 2026-09-06 23:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('display_priority', models.PositiveSmallIntegerField(default=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador comercial',
                'verbose_name_plural': 'Operadores comerciales',
                'ordering': ['display_priority', 'name'],
                'indexes': [models.Index(fields=['active', 'display_priority'], name='commercial__active_0aea19_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommercialFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=48)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=160)),
                ('display_priority', models.PositiveSmallIntegerField(default=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='commercial.commercialoperator')),
            ],
            options={
                'verbose_name': 'Familia comercial',
                'verbose_name_plural': 'Familias comerciales',
                'ordering': ['operator__display_priority', 'display_priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommercialProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commercial_name', models.CharField(max_length=120)),
                ('price_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('official_verified', models.BooleanField(db_index=True, default=False)),
                ('official_source', models.URLField(blank=True, default='', max_length=500)),
                ('official_tariff_reference', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('display_priority', models.PositiveSmallIntegerField(default=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('UNAVAILABLE', 'No disponible'), ('PROVIDER_NOT_MAPPED', 'Sin proveedor operativo'), ('PROVIDER_OFFLINE', 'Proveedor fuera de linea'), ('DISABLED', 'Deshabilitado'), ('EXPIRED', 'Vencido'), ('REVIEW_REQUIRED', 'Requiere revision'), ('SANDBOX_ONLY', 'Solo sandbox')], db_index=True, default='REVIEW_REQUIRED', max_length=24)),
                ('status_reason', models.CharField(blank=True, default='', max_length=200)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commercial.commercialfamily')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commercial.commercialoperator')),
            ],
            options={
                'verbose_name': 'Producto comercial',
                'verbose_name_plural': 'Productos comerciales',
                'ordering': ['operator__display_priority', 'family__display_priority', 'price_cents'],
            },
        ),
        migrations.CreateModel(
            name='CommercialProductVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('price_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('calls', models.CharField(blank=True, default='', max_length=200)),
                ('sms', models.CharField(blank=True, default='', max_length=200)),
                ('benefits', models.TextField(blank=True, default='')),
                ('restrictions', models.TextField(blank=True, default='')),
                ('official_source', models.URLField(blank=True, default='', max_length=500)),
                ('official_tariff_reference', models.CharField(blank=True, default='', max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='commercial.commercialproduct')),
            ],
            options={
                'verbose_name': 'Version de producto comercial',
                'verbose_name_plural': 'Versiones de producto comercial',
                'ordering': ['product', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('provider_product_id', models.CharField(max_length=128)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Produccion')], db_index=True, max_length=16)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('OK', 'Correcto'), ('REVIEW_REQUIRED', 'Requiere revision'), ('DISABLED', 'Deshabilitado')], default='REVIEW_REQUIRED', max_length=24)),
                ('status_reason', models.CharField(blank=True, default='', max_length=200)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('provider_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='commercial.commercialproduct')),
            ],
            options={
                'verbose_name': 'Mapping de proveedor',
                'verbose_name_plural': 'Mappings de proveedor',
                'ordering': ['product', 'priority', 'provider_slug'],
            },
        ),
        migrations.AddConstraint(
            model_name='commercialfamily',
            constraint=models.UniqueConstraint(fields=('operator', 'code'), name='familia_unica_por_operador'),
        ),
        migrations.AddIndex(
            model_name='commercialproduct',
            index=models.Index(fields=['operator', 'family', 'active'], name='commercial__operato_25e911_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialproduct',
            index=models.Index(fields=['active', 'official_verified', 'status'], name='commercial__active_2bea71_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercialproduct',
            constraint=models.UniqueConstraint(fields=('operator', 'family', 'commercial_name'), name='producto_comercial_unico'),
        ),
        migrations.AddConstraint(
            model_name='commercialproduct',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gt', 0)), name='producto_comercial_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='commercialproduct',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'DISABLED', 'EXPIRED', 'REVIEW_REQUIRED', 'SANDBOX_ONLY'])), name='producto_comercial_estado_administrable'),
        ),
        migrations.AddConstraint(
            model_name='commercialproductversion',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='version_unica_por_producto'),
        ),
        migrations.AddConstraint(
            model_name='commercialproductversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('product',), name='una_sola_version_vigente'),
        ),
        migrations.AddConstraint(
            model_name='commercialproductversion',
            constraint=models.CheckConstraint(condition=models.Q(('price_cents__gt', 0)), name='version_precio_positivo'),
        ),
        migrations.AddIndex(
            model_name='providerproductmapping',
            index=models.Index(fields=['provider_slug', 'environment', 'enabled'], name='commercial__provide_3e2392_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerproductmapping',
            constraint=models.UniqueConstraint(fields=('product', 'provider_slug', 'environment'), name='mapping_unico_por_producto_proveedor_ambiente'),
        ),
    ]
