# Generated by Django 5.2.17 on 2026-09-13 00:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialfamily',
            name='provider_aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commercialoperator',
            name='provider_aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='providerproductmapping',
            name='amount_in_sku',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerproductmapping',
            name='provider_amount_cents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerproductmapping',
            name='provider_family',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='providerproductmapping',
            name='provider_product_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='ProviderCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Produccion')], db_index=True, max_length=16)),
                ('provider_product_id', models.CharField(max_length=128)),
                ('provider_operator', models.CharField(blank=True, default='', max_length=120)),
                ('provider_family', models.CharField(blank=True, default='', max_length=120)),
                ('provider_product_name', models.CharField(blank=True, default='', max_length=200)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('amount_in_sku', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Producto de proveedor',
                'verbose_name_plural': 'Productos de proveedor',
                'ordering': ['provider_slug', 'environment', 'provider_product_id'],
                'indexes': [models.Index(fields=['provider_slug', 'environment', 'active'], name='commercial__provide_3f120e_idx'), models.Index(fields=['provider_operator', 'amount_cents'], name='commercial__provide_68e2dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'environment', 'provider_product_id'), name='producto_proveedor_unico_por_sku_y_ambiente')],
            },
        ),
    ]
