# Generated by Django 5.2.17 on 2026-09-13 20:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_commercialfamily_provider_aliases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(db_index=True, max_length=40)),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('PRODUCTION', 'Produccion')], db_index=True, max_length=16)),
                ('alcance', models.CharField(choices=[('OPERADOR', 'Operador'), ('SKU', 'SKU / producto'), ('INDETERMINADO', 'Indeterminado')], default='INDETERMINADO', max_length=16)),
                ('clave', models.CharField(max_length=128)),
                ('nombre', models.CharField(blank=True, default='', max_length=160)),
                ('categoria', models.CharField(blank=True, default='', max_length=120)),
                ('tasa_bps', models.IntegerField(blank=True, null=True)),
                ('tasa_texto', models.CharField(blank=True, default='', max_length=32)),
                ('exacta_en_bps', models.BooleanField(default=True)),
                ('mecanismo', models.CharField(default='SIN_DETERMINAR', help_text='Valor de samy_common.pricing.MecanismoComision. SIN_DETERMINAR hasta haberlo medido contra el saldo real.', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('observada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comision de proveedor',
                'verbose_name_plural': 'Comisiones de proveedor',
                'ordering': ['provider_slug', 'environment', 'alcance', 'nombre'],
                'indexes': [models.Index(fields=['provider_slug', 'environment', 'alcance'], name='commercial__provide_fd182a_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider_slug', 'environment', 'alcance', 'clave'), name='comision_unica_por_proveedor_ambiente_alcance_clave')],
            },
        ),
    ]
