# Generated by Django 5.2.17 on 2026-09-05 13:58

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import samy_common.states
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(db_index=True, max_length=24, unique=True)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('store_id', models.UUIDField(db_index=True)),
                ('created_by_id', models.UUIDField(db_index=True)),
                ('created_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('service_kind', models.CharField(choices=[('TOPUP', 'Recarga telefonica'), ('BILL_PAYMENT', 'Pago de servicios'), ('MERCHANT_SALE', 'Venta del comercio')], max_length=24)),
                ('fulfillment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('product_code', models.CharField(blank=True, default='', max_length=64)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('base_cents', models.BigIntegerField(help_text='Valor del servicio. Es lo que recibe el proveedor.', validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cents', models.BigIntegerField(help_text='base + comision. Lo que paga el cliente.', validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('CREATED', 'CREATED'), ('PAYMENT_PENDING', 'PAYMENT_PENDING'), ('PAID', 'PAID'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED'), ('REFUND_PENDING', 'REFUND_PENDING'), ('REFUNDED', 'REFUNDED'), ('UNDER_REVIEW', 'UNDER_REVIEW')], db_index=True, default=samy_common.states.OrderState['CREATED'], max_length=24)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_reason', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('QR', 'QR / token')], default='', max_length=16)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('provider_mode', models.CharField(blank=True, default='', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_id', '-created_at'], name='orders_orde_store_i_6d7de7_idx'), models.Index(fields=['store_id', 'state', '-created_at'], name='orders_orde_store_i_9f19e3_idx'), models.Index(fields=['created_by_id', '-created_at'], name='orders_orde_created_f3f9c3_idx'), models.Index(condition=models.Q(('state', 'PAYMENT_PENDING')), fields=['expires_at'], name='order_pending_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_cents', django.db.models.expressions.CombinedExpression(models.F('base_cents'), '+', models.F('commission_cents')))), name='order_total_equals_base_plus_commission'), models.CheckConstraint(condition=models.Q(('base_cents__gte', 0), ('commission_cents__gte', 0), ('total_cents__gte', 0)), name='order_amounts_non_negative'), models.CheckConstraint(condition=models.Q(('state__in', ['CREATED', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'EXPIRED', 'REFUND_PENDING', 'REFUNDED', 'UNDER_REVIEW'])), name='order_state_is_valid'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('store_id', 'idempotency_key'), name='order_idempotency_unique_per_store')],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('commission_cents', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('store_share_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_share_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('provider_share_cents', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rule_id', models.UUIDField(blank=True, null=True)),
                ('rule_name', models.CharField(blank=True, default='', max_length=120)),
                ('rule_description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_entry', to='orders.order')),
            ],
            options={
                'verbose_name': 'Comision aplicada',
                'verbose_name_plural': 'Comisiones aplicadas',
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_cents', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('store_share_cents'), '+', models.F('platform_share_cents')), '+', models.F('provider_share_cents')))), name='commission_shares_sum_to_total')],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_state', models.CharField(max_length=24)),
                ('new_state', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'verbose_name': 'Evento de orden',
                'verbose_name_plural': 'Eventos de orden',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4c5f76_idx')],
            },
        ),
    ]
